name: Build and Analyze
on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart Analyzer
        run: dart analyze

      - name: Compile
        run: dart compile exe bin/hrestore.dart