name: Continuous Integration (CI) Build

# This workflow is triggered on:
# 1. Pushes to any branch (for commits)
# 2. Pull Request (PR) events targeting the main branch (or any other branch you list)
on:
  push:
    branches:
      - main
      - develop
      # Add other development branches here if needed
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart Analyzer
        run: dart analyze

      - name: Compile
        run: dart compile exe bin/main.dart -o build/temp_cli_app